### ISSUE TITLE
Support for musicforprogramming.net

### ISSUE THREAD

**Issue by PeterMinin** [msfeldstein/chrome-media-keys#109]
When somebody has time, it would be nice to add a controller for [musicforprogramming.net](musicforprogramming.net).
I think the next/previous buttons should work as +/-30s when playing and, optionally, switch between the tracks when stopped.

**Comment by msfeldstein** [comment]
just pushed in 4.51 should be available soon, thanks for the suggestion, and this site is great.

**Comment by PeterMinin** [comment]
Agreed :)
Thank you!

**Comment by PeterMinin** [comment]
There's a minor problem: for some reason, the title "Music for Programming" is scrolling when I open the popup. If I press Play/Pause in it, the scrolling stops, and it's clear that the title fits in the width. If I swap the title and the artist, this starts to affect both of them.

Also, the site has a kind of album art, which can be added by a constant link:
```
controller.override('getAlbumArt', function() {
  return "http://musicforprogramming.net/img/folder.jpg"
})
```

**Comment by msfeldstein** [comment]
cool i will add this.  And yeah the marquee effect seems to have some issues which i can take a look at separately, or maybe @Ustice has an idea what the problem is.
