### ISSUE TITLE
Media keys break on extension autoupdate

### ISSUE THREAD

**Issue by achur** [msfeldstein/chrome-media-keys#25]
1. Tab open to music service, media keys working
2. Extension autoupdate occurs (simulate by unchecking, then checking enable in extensions)
3. Media keys no longer working

I believe the problem is in the following opening lines of content.coffee 

```
if window.injected then return
window.injected = true;
```

This means that when the content scripts run again on re-enabling the extension, they don't actually register the tabs, even though this is the first time the extension has run.

This makes the frequency of updates a mixed blessing, as it requires closing all music tabs and re-opening every time it happens.

**Comment by nemchik** [comment]
Possibly relevant;
http://stackoverflow.com/questions/2399389/detect-chrome-extension-first-run-update
I'm not really sure where to look to implement it though.

**Comment by mbirth** [comment]
Just noticed this during testing: When enabling the extension, the `findScriptByHost` seems to get triggered before `BasicController.js` is loaded. This results in an error about missing `BasicController` class and thus the controller isn't loaded.
