### ISSUE TITLE
Support vk.com

### ISSUE THREAD

**Issue by laughedelic** [msfeldstein/chrome-media-keys#31]
Would be nice to have support for vk.com

**Comment by nemchik** [comment]
There is a controller for vk, can anyone confirm it's working?

**Comment by msfeldstein** [comment]
I had to do a bunch of proxy into russia stuff to get this working the
first time, it would be great to have someone in russia be able to help
with this.

**Comment by PeterMinin** [comment]
This can be closed, VK is supported again since https://github.com/msfeldstein/chrome-media-keys/pull/112.
