### ISSUE TITLE
Setting Keyboard shortcut scope from 'Global' to 'In Chrome' turns media keys off 

### ISSUE THREAD

**Issue by willlma** [msfeldstein/chrome-media-keys#33]
Given the current problems with Chrome stealing the key events from native apps, I was hoping that I could just use the media keys while Chrome is the active app (in the Extension page's Keyboard shortcut panel).  

Unfortunately, the keys don't work if this setting is used (whether Chrome is the active app or not).

**Comment by msfeldstein** [comment]
Unfortunately that's another Chrome Internal bug: http://crbug.com/419607

**Comment by willlma** [comment]
Although this hasn't been completely fixed in Chrome 48, the situation is vastly improved. "In Chrome" still doesn't work, but now "Global" plays nicely with other apps.

Behavior: open Spotify, Spotify takes control of media keys irrespective of which app is in focus. Quit Spotify, Spotify relinquishes control and Chrome controls media keys irrespective of which app is in focus. I'm happy with this behavior, so closing this issue.

**Comment by msfeldstein** [comment]
That's great, this will make a lot of people happy.  Do you have a link to
details about this?

**Comment by willlma** [comment]
I don't, unfortunately. This is just my personal experience. Up until now, I manually toggled between "In Chrome" and "Global" to essentially turn this extension off and on, respectively. Then I noticed that I no longer needed to do so after updating to 48, so assumed that was the cause. Are you seeing the same thing?

**Comment by msfeldstein** [comment]
Hmm i dont think anythings changed in chrome, i think spotify just got more
aggressive with their media key capturing.  Still doesn't work in itunes.
But this is def an improvement as most bug reports mention spotify.
