### ISSUE TITLE
Public API still working?

### ISSUE THREAD

**Issue by JorritPosthuma** [msfeldstein/chrome-media-keys#38]
I cannot seem to get the public API working. Any idea what I am doing wrong? http://jsfiddle.net/jorritposthuma/ahu4dxmr/

**Comment by msfeldstein** [comment]
Hi Jorrit,
The website won't be registered until you start 'playing music' or more
accurately call sendState with playing=true.  Have you tried that?
-Michael

**Comment by msfeldstein** [comment]
Also i dont know if the api will work inside jsfiddle as it runs in a
sandboxed frame.

**Comment by JorritPosthuma** [comment]
Yes! It works!

**Comment by msfeldstein** [comment]
Where are you implementing it? I will add it to the list of supported sites

**Comment by JorritPosthuma** [comment]
An upcoming website (as in, not live yet) for synchronized SoundCloud listening. Will notify if live!
