### ISSUE TITLE
indieshuffle.com is not working

### ISSUE THREAD

**Issue by madvas** [msfeldstein/chrome-media-keys#39]
I see you've got controller for it here: https://github.com/msfeldstein/chrome-media-keys/blob/master/src/controllers/IndieshuffleController.js so I assume it should work, but unfortunately it doesn't. I'm using Chrome 42, OS X Yosemite. Other websites work great, good job!

Thanks

**Comment by msfeldstein** [comment]
Thanks for the heads up.  Pushing v3.86 with a fix now, should be live in an hour or so.

**Comment by madvas** [comment]
Wow this was ultra fast, thanks!
