### ISSUE TITLE
Media Stop Key

### ISSUE THREAD

**Issue by nemchik** [msfeldstein/chrome-media-keys#42]
I frequently use a macro to send a stop keypress ( VK_MEDIA_STOP or 0xB2 according to https://msdn.microsoft.com/en-us/library/dd375731(VS.85).aspx ) and it would be nice if this extension could support this.

The idea would be the stop key pauses the music, but does not play the music.

I use this functionality kind of like a "boss key" if you will, i press a button and my music stops and some other actions happen as well. This doesnt work if I use play/pause because if i'm not playing music and I hit my "boss key" music will start rather than stop if i use play/pause. I've worked with another media key extension for chrome and was able to implement this functionality but the pull request was never accepted. Before I go digging through the code of this extension I was wondering if this would be easy for any existing contributors to add.

**Comment by msfeldstein** [comment]
It shouldn't be too tough to add, you'll basically want to look here
<https://github.com/msfeldstein/chrome-media-keys/blob/master/src/content_scripts/content.coffee#L98>
and
check for the stop button, and then check if controller.isPlaying() then
call pause if so.  You'll also need to add the stop command to the
manifest.  I can do this later but if you feel like getting it done faster
I'm happy to do a pull request.  Actually it's probably better if you do
it, as I don't have a stop key to test it with.
-Michael

**Comment by nemchik** [comment]
I'll give it a shot. I am not sure what you mean by "call pause". I was thinking `if (request.action is "stop" && controller.isPlaying()) then controller.play()` but this might not be right.

I actually don't have a physical stop button, but I have a logitech headset with programmable media keys and macro support. I'm using http://nircmd.nirsoft.net/ in a macro in the context `nircmd sendkeypress 0xB2` to send a media stop key.

**Comment by nemchik** [comment]
I'm trying to load the unpacked extension and it's complaining about background.html missing. I don't see that file in the source but it is named in the manifest. I'm also a rookie with chrome extensions, so i might just be doing something wrong. I turned on developer mode and tried to load the unpacked extension in the src folder.

**Comment by msfeldstein** [comment]
It needs to be built with grunt, check out the readme:
https://github.com/msfeldstein/chrome-media-keys/blob/master/README.md

**Comment by nemchik** [comment]
Ok, I got nodejs installed (for npm) and ruby, and the haml gem, and i made it to `grunt run` and it stops at
```
Running "watch" task
Waiting...
```
What next? (sorry i have never used nodejs, or ruby, or grunt, lol)

**Comment by msfeldstein** [comment]
i guess i should make the instructions a little more clear.  Now there
should be an ext/ folder next to src/  this is the actual installable
extension.  If you install the unpacked extension in the ext/ directory it
should work.  Also anytime you make a change to the source code, it will
recompile to ext.  You should then just have to click "reload" on the
extension page to see the changes (as well as reload any music players).

Never make changes directly to the ext/ files as that directory gets
overwritten often.

**Comment by nemchik** [comment]
Gotcha, so as long as I leave my shell open with the watch it will update the ext/ folder automatically? (that's nice!) and if i make any commits i should just make sure not to commit the ext/ folder im guessing?

**Comment by nemchik** [comment]
Well I added stop to the manifest (and I see it in the keyboard shortcuts) and I added stop to the content.coffee file and set it to `controller.play()` just to make sure it would work, but it doesnt. I expect it would make the stop key act exactly like the pause key. Instead it seems the stop key does nothing. Maybe i'm still missing something.

**Comment by msfeldstein** [comment]
You shouldn't have to worry about committing the ext folder, its in gitignore.  And yes as long as you leave the terminal running with grunt run it'll keep compiling.

And yes, i guess it is controller.play().  I guess i should have called that playPause().  Nothing is happening when you call controller.play()?  Are you sure the code is getting there?  You can run a console.log in there and inspect the page its running in to make sure.  Also make sure that you reload the music player so that commands are sent to it after reloading the extension.

**Comment by nemchik** [comment]
I'll check the console log soon. I disabled the stable plugin from the store, enabled and reloaded the unpacked plugin from ext/ which had my changes, and then reloaded my player (I tried sound cloud) and the other media keys worked (play/pause, etc) but stop didn't work.
The changes I made to the manifest were just to copy the code for "next" and replace things to make it stop, chrome recognized this in it's keyboard shortcuts. In the content.coffee I copied the pause line and replaced the word pause with stop.

**Comment by nemchik** [comment]
OK I did a `console.log()` for my stop key and i got nothing, i also modified the pause button to do the pause action and a `console.log()` and the pause function works and logs. so the key isnt being passed.
btw i can use my physical play/pause key or i can use `nircmd sendkeypress 0xB3`, while the stop would be `0xB2`
Here is my initial commit just so you can see where i'm at. https://github.com/nemchik/chrome-media-keys/commit/3eabccc9b9f96a9bf4bf12645f3629e56b8bced2 If I can figure it our i'll finish it, test it, and make a PR

**Comment by darthwalsh** [comment]
In case anybody else reads this thread, I went down a rabbithole debugging why `nircmd sendkeypress 0xB3` wasn't triggering the play/pause chrome global hotkey -- maybe because my keyboard doesn't have physical media keys, but nircmd wasn't correctly sending media play pause. You can run `Send, {Media_Play_Pause}` in autohotkey which **will** trigger the play/pause chrome command.
