### ISSUE TITLE
Document BasicController

### ISSUE THREAD

**Issue by nemchik** [msfeldstein/chrome-media-keys#49]
There seem to be a ton of options that aren't laid out in any template or anything. It would be great to have a template and comments about what each property does. Maybe also mention the override capability.

Hopefully this will make it easier for contributors to maintain controllers over time.

**Comment by msfeldstein** [comment]
Added some more comments in e5e1ab0bdfb6ec91fa2a21fe37da32fa5091d06b

There's some things like "doThrottling" that i'll probably remove (we should always do throttling) i just want to make sure it doesn't break anything

**Comment by nemchik** [comment]
referencing https://github.com/msfeldstein/chrome-media-keys/pull/52

**Comment by msfeldstein** [comment]
I think #52 solves this.
