### ISSUE TITLE
Plex Media Server / Web App

### ISSUE THREAD

**Issue by karbowiak** [msfeldstein/chrome-media-keys#6]
Hi..

The Plex developers FINALLY added Shuffle to their media server, which also works in their webapp.

Any possibility that you might add support for Plex in Sway? :)

Keys:
```
Space = Play / Pause
down = Volume Down
up = Volume Up
, (comma) = seek back
. (dot) = seek ahead
left = previous
right = next
```

**Comment by msfeldstein** [comment]
@mbirth just posted a patch for this i will push out 4.45 shortly
