### ISSUE TITLE
Scrobbling always gives 'Null' as artist on soundcloud

### ISSUE THREAD

**Issue by joshkaplan** [msfeldstein/chrome-media-keys#65]
I have only tried SoundCloud, but problem may exist for other services as well. 
![screenshot 2015-06-17 14 17 43](https://cloud.githubusercontent.com/assets/5589260/8218989/b9257e38-14fb-11e5-8e5d-e14c945a05bb.png)

**Comment by msfeldstein** [comment]
For something like soundcloud where there isn't really a clear separation between artist and title, would it be appropriate to just put the whole track name in the track title and just not send an artist?

**Comment by joshkaplan** [comment]
Hmm yeah it's tough. Could probably throw together some regex that tries to parse it out, not sure how error prone it would be tho

**Comment by msfeldstein** [comment]
I just pushed v4.12 which has a simple version of artist / title splitting,
it should work well for most cases, and also return an empty string instead
of null when it can't.  Should keep your scrobblelist cleaner.  Let me know
what you think!

**Comment by joshkaplan** [comment]
Looks good to me!
