### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ahmedalsudani** [msfeldstein/chrome-media-keys#72]
Is it possible to add an open-source license to this project?

I understand if that's not something you'd want to do, but it would make me -- and I assume others -- feel more comfortable contributing.

**Comment by msfeldstein** [comment]
Sure its not something i'm all too familiar with, do you have any suggestions as to which one?

**Comment by ahmedalsudani** [comment]
I'm very happy to hear that :smile: 

http://choosealicense.com/ has good primers.

IMHO, if you want something permissive, MIT would do. It allows anyone to do anything with your code as long as they attribute it to you and do not hold you liable.

If you want to require that whoever uses your code contribute back their changes, AGPL is the way to go. It's a little more cumbersome if someone wants to incorporate your work into their products though.

Let me know if you want me to make a PR with whichever license you pick.

**Comment by msfeldstein** [comment]
I think AGPL looks best to me.  That's a great site btw.  I'm happy to
accept a pr for that.

**Comment by msfeldstein** [comment]
do you have a project in mind you want to integrate it with?

**Comment by ahmedalsudani** [comment]
@msfeldstein nope, nothing in mind. I was just comparing the two licenses in general.

I've been using it for my own listening, and it's been wonderful. Thanks for creating and maintaining it!
