### ISSUE TITLE
Dynamic support flags

### ISSUE THREAD

**Issue by PeterMinin** [msfeldstein/chrome-media-keys#78]
This may already be implemented, but I haven't found this feature. Is there a way for a controller to determine the availability of buttons like, for example, "thumbs down" dynamically, using a custom function? One service (namely Yandex.Music) has 2 playing modes, one of which has a dislike button, while the other doesn't.

**Comment by msfeldstein** [comment]
You should just be able to update the 'supports' object of the controller, and it should be reflected in the popup.  It probably wont live update, but if you close and open the popup it should be fine.  Is this not the case?

**Comment by PeterMinin** [comment]
Thank you, it works, although I couldn't find a better place to do it than an overridden `isPlaying`:

    controller.defaultIsPlaying = controller.isPlaying
    controller.override('isPlaying', function() {
        this.supports.thumbsDown = window.getComputedStyle(document.querySelector(this.thumbsDownSelector)).display != 'none'
        return this.defaultIsPlaying()
    });

It even live updates, but is there a more appropriate place?

**Comment by msfeldstein** [comment]
You can add a dom listener for the change they makes you switch modes but
what you did is probably more performing. Also when you override a function
the default implementation is passed in as the first argument. See
GoogleMusicController

**Comment by PeterMinin** [comment]
Oh, thanks, I don't have much JS experience.
Then I guess I'll leave it here for performance sake.
