### ISSUE TITLE
Support chrome apps

### ISSUE THREAD

**Issue by matthewdias** [msfeldstein/chrome-media-keys#80]
Add support for chrome apps that are wrappers for already compatible sites. Maybe this can be achieved by checking if WindowType is "app" ?

**Comment by msfeldstein** [comment]
Do you have an example?  I think there's a security issue where you can't inject code into packaged apps, only regular webpages, though that may have changed in the past couple of years, im willing to try again

**Comment by matthewdias** [comment]
I read up a little more and it still doesn't seem like it's possible.
