### ISSUE TITLE
Amazon music not working

### ISSUE THREAD

**Issue by timwood** [msfeldstein/chrome-media-keys#81]
For a month or two now the Chrome extension [Media Keys by Sway.fm](https://chrome.google.com/webstore/detail/media-keys-by-swayfm/icckhjgjjompfgoiidainoapgjepncej) hasn't been working with Amazon Music cloud player. There used to be a support tab on the extension page but that has been removed and only Overview, Reviews and Related are left. Before it was removed I noticed a few other users commenting with the same issue. Also Sway.fm doesn't resolved, isn't registered and obviously the support email won't work as a result. The Twitter account is still up at https://twitter.com/swayfm.

Does anyone involved in this OSS project know whether the published plugin is maintained anymore or if there is an alternative that works well?

Thanks!

**Comment by msfeldstein** [comment]
Hey I'm maintaining it, sorry for the domain issues, godaddy is killing me
slowly.

I don't have access to amazon music, if someone is willing to share their
password with me, or if anyone wants to make a pull request to fix I'm
happy to do so.

**Comment by timwood** [comment]
Ugh, godaddy, sorry to hear that.

I think you can use the [Amazon music player](https://www.amazon.com/gp/dmusic/cloudplayer/player) if you own (or upload?) a single song on Amazon. They even have some free music. Right now Foo Fighters are giving away their latest EP: https://www.amazon.com/gp/product/B0186SDOP0 and there are lots of other free albums here: http://www.amazon.com/s?rh=n:318774011,p_n_feature_browse-bin:625150011

Thanks for a great chrome extension!

**Comment by msfeldstein** [comment]
oh nice!  Is this the same player? 
![screen shot 2016-01-11 at 2 23 21 pm](https://cloud.githubusercontent.com/assets/161135/12248531/eefdb82e-b86e-11e5-977b-28e677f148d1.png)

**Comment by msfeldstein** [comment]
Thanks for you help!  I pushed a fix in [ba989b2] and submitted v4.39 to the app store, it should be out in an hour.

**Comment by timwood** [comment]
Looks the same to me. Thanks for working on a fix so quick!
