### ISSUE TITLE
Uncaught ReferenceError: controller is not defined

### ISSUE THREAD

**Issue by ckhatton** [msfeldstein/chrome-media-keys#82]
An error keeps appearing in the web console on `line 63` of `/content_scripts/content.js`.

The 'controller' variable is undefined on every webpage, even those that this extension is built for.

:octocat:

**Comment by msfeldstein** [comment]
What version are you on?

**Comment by msfeldstein** [comment]
are you installed through the store or by building?  I'm not able to repro this

**Comment by ckhatton** [comment]
Hi @msfeldstein 
v4.41 Installed via the store.
:cake:

**Comment by msfeldstein** [comment]
Hmm looks like something got corrupted in publishing. I just pushed 4.42
will you let me know if that still doesn't work?

**Comment by ckhatton** [comment]
Yea, that seems to have fixed it :+1: Danke schön! :octocat:

**Comment by mbirth** [comment]
So can this be closed then?
