### ISSUE TITLE
Pocket Casts support

### ISSUE THREAD

**Issue by mbirth** [msfeldstein/chrome-media-keys#85]
Please add support for the Pocket Casts web player: https://play.pocketcasts.com/web

**Comment by msfeldstein** [comment]
Hey markus,
Since this is a paid service, I'd need to borrow someone's account to fix it up.  Or if you're a developer you can also fix it and make a PR, it used to work so it should be a simple fix.

**Comment by mbirth** [comment]
I didn't find a Pocket Casts controller file to fix. But the format looks easy, I'll try to add it.

**Comment by msfeldstein** [comment]
Ah weird i could have sworn i had added it.  Oh well, the steps are to add
a file under controllers to map the buttons to css selectors, then add the
domain-file mapping here:
https://github.com/msfeldstein/chrome-media-keys/blob/master/src/background/mappings.coffee
22tracks shows a good example of a basic controller.

**Comment by mbirth** [comment]
Works fine now.
